
name: تشغيل بوت تيليجرام

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: استنساخ المستودع
        uses: actions/checkout@v4

      - name: إعداد بايثون
        uses: actions/setup-python@v4
        with:
          python-version:  3.x 

      - name: تثبيت المتطلبات
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: التحقق من المتغيرات البيئية
        run: |
          if [ -z "${{ secrets.TOKEN }}" ]; then
            echo "الرمز المميز (TOKEN) غير محدد!"
            exit 1
          fi

      - name: تشغيل البوت
        run: python bot.py
